config/routes.rb
Rails.application.routes.draw do
  resources :agendas
  resources :records
  get 'users/new'
  post 'records/new'
  post 'users/add_loss'
  post 'users/add_victory'


  resources :categories
  resources :users
  resources :records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "categories#h2h"
  get '/h2h', to: 'categories#h2h'
  get '/categories', to: 'categories#index'
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/records', to: 'records#index'
  get '/profile/:id', to: 'users#profile', as: 'profile'
  post '/profile/:id/add_loss', to: 'users#add_loss'
  post '/profile/:id/add_victory', to: 'users#add_victory'
  post '/signup', to: 'users#create'
  get '/leaderboard', to: 'records#leaderboard', as: 'leaderboard'
  get '/leaderboard/add_victory', to: 'records#add_victory'
  get '/leaderboard/add_loss', to: 'records#add_loss'
  post '/leaderboard/add_victory', to: 'records#add_victory'
  post '/leaderboard/add_loss', to: 'records#add_loss'
  get '/agenda', to: 'agendas#index'

end

app/models/user.rb
class User < ApplicationRecord
	has_many :records, class_name: "Record", foreign_key: "user_id"
	has_many :competitor_user_records, class_name: "Record", foreign_key: "competitor_user_id"
	has_many :categories

	before_save { self.email = self.email.downcase }
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 100}, 
		format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6}

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def profile
    @user = User.find(params[:id])
    @record = Record.where(user_id: @user.id)
  end

  def add_victory
    @recordid = Record.find_by_id(params[:id])
    @record_category_id = @recordid.category_id
    @competitor_user_id = @recordid.competitor_user_id  
    @competitor_record_id = Record.where("user_id LIKE ? AND category_id LIKE ?", @competitor_user_id, @record_category_id).first
      # puts "Record Category identifier is " + @record_category_id.inspect
      # puts "Competitor User identifier is " + @competitor_user_id.inspect
      # puts "Competitor Record identifier is " + @competitor_record_id.inspect
      # puts "User id: " + @recordid.user_id.inspect
    
    @recordid.wins +=1

    if @competitor_record_id === nil
      # Create Competitor Record if it does not exist
      Record.create(:user_id =>  @competitor_user_id, :category_id => @recordid.category_id, 
          :competitor_user_id => @recordid.user_id, :wins => 0, :losses => 1)
      redirect_back(fallback_location: records_path)
    else 
      # Add loss to opponent
      @competitor_record_id.losses +=1 
      if @recordid.save & @competitor_record_id.save
        redirect_back(fallback_location: records_path)
      end
    end     
  end

  def add_loss
    @recordid = Record.find_by_id(params[:id])
    @record_category_id = @recordid.category_id
    @competitor_user_id = @recordid.competitor_user_id  
    @competitor_record_id = Record.where("user_id LIKE ? AND category_id LIKE ?", @competitor_user_id, @record_category_id).first
    
    @recordid.losses +=1

      if @competitor_record_id === nil
        # Create Competitor Record if it does not exist
        Record.create(:user_id =>  @competitor_user_id, :category_id => @recordid.category_id, 
          :competitor_user_id => @recordid.user_id, :wins => 1, :losses => 0)
        redirect_back(fallback_location: records_path)
      else
        # Add win to opponent
        @competitor_record_id.wins +=1 
        if @recordid.save & @competitor_record_id.save
          redirect_back(fallback_location: records_path)
        end
      end
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Welcome to the betting pit!"
  		redirect_to user_url(@user)
  	else
  		render 'new'
  	end
  end

  private

  	def user_params
  		params.require(:user).permit(:name, :email, :password,
  			:password_confirmation)
  	end

end

app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar for the given user
	def gravatar_for(user, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: 'gravatar')
	end

end

app/views/users/index.html.erb
<%= render 'shared/nav' %>
<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |usr| %>
      <tr>
        <td><%= usr.name %></td>

        <td><%= link_to 'Profile', profile_path(usr) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'shared/nav' %>
<h1>Sign up</h1>

<div class="row">
	<%= form_for(@user, url: signup_path ) do |f| %>
		<%= render 'shared/error_messages' %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.email_field :email %>

		<%= f.label :password %>
		<%= f.password_field :password %>

		<%= f.label :password_confirmation, "Password Confirmation" %>
		<%= f.password_field :password_confirmation %>

		<%= f.submit "Create account", class: "btn btn-primary" %>
	<% end %> 
</div>

app/views/users/profile.html.erb
<%= render 'shared/nav' %>
<h1><%= @user.name %></h1>



<table class=" table table-striped sortable" border="1px solid black">
  <thead>
    <tr>
      <th>Category</th>
      <th>User</th>
      <th>Opponent</th>
      <th>Wins</th>
      <th>Losses</th>
    </tr>
  </thead>

 <tbody>
   <% @record.each do |user_record| %>
     <tr>
      <td><%= user_record.user.name %></td>
      <td><%= user_record.category.category %></td>
      <td><%= user_record.competitor_user.name %></td>
      <td><%= user_record.wins %> <%= button_to "Add Victory", :action => "add_victory", :id => user_record.id %></td>
      <td><%= user_record.losses %> <%= button_to "Add Loss", :action => "add_loss", :id => user_record.id %></td>
    </tr>
   <% end %>
 </tbody>

app/views/users/show.html.erb
<%= render 'shared/nav' %>
<% provide(:title, @user.name) %>
<h1>
	<%= gravatar_for @user %>
	<%= @user.name %>
</h1>