config/routes.rb
Rails.application.routes.draw do
  resources :agendas
  resources :records
  get 'users/new'
  post 'records/new'
  post 'users/add_loss'
  post 'users/add_victory'


  resources :categories
  resources :users
  resources :records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "categories#h2h"
  get '/h2h', to: 'categories#h2h'
  get '/categories', to: 'categories#index'
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/records', to: 'records#index'
  get '/profile/:id', to: 'users#profile', as: 'profile'
  post '/profile/:id/add_loss', to: 'users#add_loss'
  post '/profile/:id/add_victory', to: 'users#add_victory'
  post '/signup', to: 'users#create'
  get '/leaderboard', to: 'records#leaderboard', as: 'leaderboard'
  get '/leaderboard/add_victory', to: 'records#add_victory'
  get '/leaderboard/add_loss', to: 'records#add_loss'
  post '/leaderboard/add_victory', to: 'records#add_victory'
  post '/leaderboard/add_loss', to: 'records#add_loss'
  get '/agenda', to: 'agendas#index'

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(@user.errors.count, "error") %>.
		</div>
		<ul>
		<% @user.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_nav.html.erb
<%= link_to 'Categories', categories_path %>
<%= link_to 'Create Category', new_category_path %>
<%= link_to 'Profiles', users_path %>
<%= link_to 'Create Profiles', new_user_path %>
<%= link_to 'Record List', records_path %>
<%= link_to 'Create New Record', new_record_path %>
<%= link_to 'Leaderboard', leaderboard_path %>
<%= link_to 'Agenda', agendas_path %>