config/routes.rb
Rails.application.routes.draw do
  resources :agendas
  resources :records
  get 'users/new'
  post 'records/new'
  post 'users/add_loss'
  post 'users/add_victory'


  resources :categories
  resources :users
  resources :records
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "categories#h2h"
  get '/h2h', to: 'categories#h2h'
  get '/categories', to: 'categories#index'
  get '/users', to: 'users#index'
  get '/signup', to: 'users#new'
  get '/records', to: 'records#index'
  get '/profile/:id', to: 'users#profile', as: 'profile'
  post '/profile/:id/add_loss', to: 'users#add_loss'
  post '/profile/:id/add_victory', to: 'users#add_victory'
  post '/signup', to: 'users#create'
  get '/leaderboard', to: 'records#leaderboard', as: 'leaderboard'
  get '/leaderboard/add_victory', to: 'records#add_victory'
  get '/leaderboard/add_loss', to: 'records#add_loss'
  post '/leaderboard/add_victory', to: 'records#add_victory'
  post '/leaderboard/add_loss', to: 'records#add_loss'
  get '/agenda', to: 'agendas#index'

end

app/models/agenda.rb
class Agenda < ApplicationRecord
end

app/controllers/agendas_controller.rb
class AgendasController < ApplicationController
  before_action :set_agenda, only: [:show, :edit, :update, :destroy]

  # GET /agendas
  # GET /agendas.json
  def index
    @agendas = Agenda.all
  end

  # GET /agendas/1
  # GET /agendas/1.json
  def show
  end

  # GET /agendas/new
  def new
    @agenda = Agenda.new
  end

  # GET /agendas/1/edit
  def edit
  end

  # POST /agendas
  # POST /agendas.json
  def create
    @agenda = Agenda.new(agenda_params)

    respond_to do |format|
      if @agenda.save
        format.html { redirect_to @agenda, notice: 'Agenda was successfully created.' }
        format.json { render :show, status: :created, location: @agenda }
      else
        format.html { render :new }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /agendas/1
  # PATCH/PUT /agendas/1.json
  def update
    respond_to do |format|
      if @agenda.update(agenda_params)
        format.html { redirect_to @agenda, notice: 'Agenda was successfully updated.' }
        format.json { render :show, status: :ok, location: @agenda }
      else
        format.html { render :edit }
        format.json { render json: @agenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /agendas/1
  # DELETE /agendas/1.json
  def destroy
    @agenda.destroy
    respond_to do |format|
      format.html { redirect_to agendas_url, notice: 'Agenda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agenda
      @agenda = Agenda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def agenda_params
      params.require(:agenda).permit(:agenda_item, :is_complete)
    end
end

app/helpers/agendas_helper.rb
module AgendasHelper
end

app/views/agendas/_form.html.erb
<%= form_with(model: agenda, local: true) do |form| %>
  <% if agenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(agenda.errors.count, "error") %> prohibited this agenda from being saved:</h2>

      <ul>
      <% agenda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :agenda_item %>
    <%= form.text_field :agenda_item, id: :agenda_agenda_item %>
  </div>

  <div class="field">
    <%= form.label :is_complete %>
    <%= form.check_box :is_complete, id: :agenda_is_complete %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/agendas/edit.html.erb
<h1>Editing Agenda</h1>

<%= render 'form', agenda: @agenda %>

<%= link_to 'Show', @agenda %> |
<%= link_to 'Back', agendas_path %>

app/views/agendas/index.html.erb
<%= render 'shared/nav' %>
<p id="notice"><%= notice %></p>

<h1>Agenda</h1> 
<%= link_to 'New Agenda Item', new_agenda_path %>
<p>
<table border = "1px solid black">
  <thead>
    <tr>
      <th>Agenda item</th>
      <th>Complete?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @agendas.each do |agenda| %>
      <tr>
        <td><%= agenda.agenda_item %></td>
        <td><%= agenda.is_complete %></td>
        <td><%= link_to 'Show', agenda %></td>
        <td><%= link_to 'Edit', edit_agenda_path(agenda) %></td>
        <td><%= link_to 'Destroy', agenda, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/agendas/new.html.erb
<h1>New Agenda</h1>

<%= render 'form', agenda: @agenda %>

<%= link_to 'Back', agendas_path %>

app/views/agendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Agenda item:</strong>
  <%= @agenda.agenda_item %>
</p>

<p>
  <strong>Is complete:</strong>
  <%= @agenda.is_complete %>
</p>

<%= link_to 'Edit', edit_agenda_path(@agenda) %> |
<%= link_to 'Back', agendas_path %>